version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgres_gis
    environment:
      POSTGRES_DB: restoran
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_NAME=restoran
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432

volumes:
  postgres_data:
