# Generated by Django 5.0.6 on 2024-05-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_alter_diagnosishistory_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='licenses/restoraunt')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='diagnosis.doctor')),
            ],
        ),
    ]
