# Generated by Django 5.0.6 on 2024-05-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_doctorphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(related_name='services', to='diagnosis.service'),
        ),
    ]
