# Generated by Django 5.0.6 on 2024-05-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_dishes_appointment_services_appointment_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminarydiagnosis',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='prebuyed_dishes', to='diagnosis.dishes'),
        ),
        migrations.AddField(
            model_name='preliminarydiagnosis',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='prebuyed_services', to='diagnosis.service'),
        ),
    ]
