# Generated by Django 5.0.6 on 2024-05-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_preliminarydiagnosis_dishes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosishistory',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='bb_dishes', to='diagnosis.dishes'),
        ),
        migrations.AddField(
            model_name='diagnosishistory',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='bb_services', to='diagnosis.service'),
        ),
        migrations.AddField(
            model_name='diagnosishistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
