# Generated by Django 5.0.6 on 2024-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_diagnosishistory_dishes_diagnosishistory_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
